#!/bin/bash

# let user choose a version otherwise default to most recent
[ -z "$SBT_VER" ] && SBT_VER="0.13.9"

# download sbt
wget "https://dl.bintray.com/sbt/native-packages/sbt/$SBT_VER/sbt-$SBT_VER.zip"

# extract
unzip -q "sbt-*.zip" -d "$PWD/sbt-pkg"

# add bin to path
PATH="$PATH:$PWD/sbt-pkg/sbt/bin"

# compile project
sbt compile
